import type { TalentStat } from "../../../../engine/types"

export const TALENT_STAT_LABELS: Readonly<Record<TalentStat, string>> = {
  minPhys: "Min Phys",
  maxPhys: "Max Phys",
  physPenetration: "Phys Penetration",
  minBellstrike: "Min Bellstrike",
  maxBellstrike: "Max Bellstrike",
  bellstrikePenetration: "Bellstrike Penetration",
  minStonesplit: "Min Stonesplit",
  maxStonesplit: "Max Stonesplit",
  stonesplitPenetration: "Stonesplit Penetration",
  minSilkbind: "Min Silkbind",
  maxSilkbind: "Max Silkbind",
  silkbindPenetration: "Silkbind Penetration",
  minBamboocut: "Min Bamboocut",
  maxBamboocut: "Max Bamboocut",
  bamboocutPenetration: "Bamboocut Penetration",
  precisionRate: "Precision Rate",
  critRate: "Crit Rate",
  affinityRate: "Affinity Rate",
  critDamage: "Crit Damage",
  affinityDamage: "Affinity Damage",
  attributeDamage: "Attribute Damage",
}
