import { createRequire } from "node:module"
import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const require = createRequire(import.meta.url)

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const officialMap = require(join(repoRoot, "reference/gear/officialAffixMap.json"))

const TABLE_OUT = "src/ui/features/gear/import-gear-dialog/affixStatLineTable.ts"

// The one place the official map's vocabulary is joined to ours. A value absent
// here is left out of the table, so an affix can never resolve to an id no
// `AttunementOption` or gear word declares.
const OFFICIAL_TO_TARGET = {
  affinity: "word:affinity",
  agility: "word:agility",
  allWeaponDmg: "word:allMartialBoost",
  areaDebuffMysticDmg: "word:areaMysticBoost",
  areaDmgMysticDmg: "word:areaMysticBoost",
  areaMysticDmg: "word:areaMysticBoost",
  bleed: "attunement:bleedingDamage",
  bossDmg: "word:damageVsBoss",
  crit: "word:crit",
  dualBladesDmg: "word:dualKnivesBoost",
  fanDmg: "word:fanBoost",
  formlessPen: "attunement:formlessPen",
  hengBladeDmg: "word:hengDaoBoost",
  maxBamboocut: "word:maxBamboocut",
  maxBellstrike: "word:maxBellstrike",
  maxPhys: "word:maxPhys",
  maxSilkbind: "word:maxSilkbind",
  maxStonesplit: "word:maxStonesplit",
  maxVoid: "word:maxVoidAttack",
  minBamboocut: "word:minBamboocut",
  minBellstrike: "word:minBellstrike",
  minPhys: "word:minPhys",
  minSilkbind: "word:minSilkbind",
  minStonesplit: "word:minStonesplit",
  minVoid: "word:minVoidAttack",
  moBladeDmg: "word:modaoBoost",
  momentum: "word:momentum",
  phalanxbaneCharged: "attunement:phalanxChargeDamage",
  phalanxbaneQ: "attunement:phalanxbaneQ",
  physPen: "attunement:physPen",
  physResist: "attunement:physResist",
  power: "word:power",
  precision: "word:precision",
  ropeDartDmg: "word:ropeDartBoost",
  snowpartingCharged: "attunement:snowpartingCharged",
  snowpartingQ: "attunement:snowpartingQ",
  snowpartingVariedCombo: "attunement:snowpartingVariedCombo",
  spearCharged: "attunement:spearCharged",
  spearDmg: "word:spearBoost",
  spearQ: "attunement:spearQ",
  stBurstMysticDmg: "word:singleTargetMysticBoost",
  stControlMysticDmg: "word:singleTargetMysticBoost",
  stMysticDmg: "word:singleTargetMysticBoost",
  swordCharged: "attunement:swordCharged",
  swordDmg: "word:swordBoost",
  swordQ: "attunement:swordQ",
  swordSpecial: "attunement:swordSpecial",
  umbrellaDmg: "word:umbrellaBoost",
}

// `dashboardGearPayload.ts` classifies by id alone: an affix below this is an
// attunement, at or above it a gear word. An entry whose target contradicts
// that could never resolve, so it is dropped rather than shipped as a mapping
// the runtime will always reject.
const LOWEST_WORD_AFFIX_ID = 1_000_000

const entries = []
const skipped = new Map()
const misclassified = new Map()
for (const affixId of Object.keys(officialMap).sort()) {
  const official = officialMap[affixId]
  const target = OFFICIAL_TO_TARGET[official]
  if (!target) {
    skipped.set(official, (skipped.get(official) ?? 0) + 1)
    continue
  }
  const isAttunementId = Number(affixId) < LOWEST_WORD_AFFIX_ID
  if (target.startsWith("attunement:") !== isAttunementId) {
    misclassified.set(official, (misclassified.get(official) ?? 0) + 1)
    continue
  }
  entries.push(`  "${affixId}": "${target}",`)
}

const source = [
  "// Generated by scripts/generateAffixStatLineTable.mjs from",
  "// reference/gear/officialAffixMap.json — edit the mapping in that script, not",
  "// this table. An affix the map names but our stat lines do not model is left",
  "// out, so the import dialog offers it as an unmapped choice instead of",
  "// resolving it to an id nothing declares.",
  "export const AFFIX_ID_TO_STAT_LINE: Readonly<Record<string, string>> = {",
  ...entries,
  "}",
  "",
].join("\n")

writeFileSync(join(repoRoot, TABLE_OUT), source)

console.log(`official affixes: ${Object.keys(officialMap).length}`)
console.log(`mapped: ${entries.length}`)
console.log(`left unmapped: ${[...skipped.values()].reduce((sum, count) => sum + count, 0)}`)
console.log(
  `dropped as id/target mismatches: ${[...misclassified.values()].reduce((sum, count) => sum + count, 0)}` +
    ` (${[...misclassified.keys()].sort().join(", ")})`,
)
console.log(`distinct unmapped names: ${[...skipped.keys()].sort().join(", ")}`)
